PRINT "How I Start My Mornings "; "[Sequential Logic]"
PRINT
PRINT "wake up at 6:00am"
PRINT "get out of bed"
PRINT "reach for phone"
PRINT "dismiss alarm"
PRINT "walk to closet"
PRINT "put on clothes"
PRINT "put on house shoes"
PRINT "pocket phone"
PRINT "exit: bedroom door"
PRINT "turn R"
PRINT "walk to my office"
PRINT "enter: office door"
PRINT "wake up computer"
PRINT "walk around corner desk"
PRINT "go to chair"
PRINT "sit down"
PRINT "place phone on stand"
PRINT "turn on monitor"
PRINT "type in PIN on PC"
PRINT "get comfy"
PRINT "set discord status: online"
PRINT "check msgs on phone and discord"
PRINT "drink some water"
PRINT "load up morning (tv media)"
PRINT "grab water cup"
PRINT "grab coffee mug"
PRINT "walk to door"
PRINT "set down coffee mug"
PRINT "open office door"
PRINT "grab coffee mug"
PRINT "walk up stairs"
PRINT "place cups on counter"
PRINT "turn on stove light"
PRINT "look at cat"
PRINT "pet cat"
PRINT "grab glass kettle on stove"
PRINT "open fridge"
PRINT "fill with water"
PRINT "place back on stove"
PRINT "turn on stove: max temp"
PRINT "open fridge"
PRINT "operate water purifier"
PRINT "refill water cup"
PRINT "close fridge"
PRINT "drink some more"
PRINT "place water on counter"
PRINT "walk to other side of kitchen"
PRINT "open top right cabinet"
PRINT "grab large plate"
PRINT "close cabinet"
PRINT "set plate by toaster"
PRINT "walk back to fridge"
PRINT "open fridge"
PRINT "grab loaf of bread"
PRINT "close fridge"
PRINT "walk back to toaster"
PRINT "undo plastic clamp"
PRINT "unwarp bag"
PRINT "set plastic clamp down"
PRINT "set loaf down"
PRINT "take two bread slices"
PRINT "place in toaster"
PRINT "turn on toaster"
PRINT "adjust temp to my usual setting"
PRINT "re-apply clamp to bread bag"
PRINT "walk to fridge"
PRINT "open fridge"
PRINT "set loaf back"
PRINT "grab strawberry jam"
PRINT "close fridge"
PRINT "walk to toaster"
PRINT "place next to plate"
PRINT "reach down"
PRINT "open utensil drawer"
PRINT "grab favorite knife"
PRINT "place knife on plate"
PRINT "walk to stove"
PRINT "open cabinet next to stove"
PRINT "take out coffee container"
PRINT "put some in cup"
PRINT "begin waiting"
PRINT "become amused at cat"
PRINT "walk to pantry"
PRINT "enter: pantry"
PRINT "reach in"
PRINT "grab cat food"
PRINT "exit: pantry"
PRINT "walk to cat's bowl"
PRINT "reach down"
PRINT "clean if needed"
PRINT "place on counter"
PRINT "open cat food"
PRINT "quickly toss leftovers"
PRINT "empty can's contents in bowl"
PRINT "throw out can trash"
PRINT "grab bowl"
PRINT "reach down"
PRINT "place bowl on floor"
PRINT "watch cat chow down"
PRINT "pet him again"
PRINT "hear toaster ding"
PRINT "walk to toaster"
PRINT "grab bread"
PRINT "put it on plate"
PRINT "equip knife"
PRINT "open top cabinet"
PRINT "get a scoop of butter"
PRINT "place butter on knife"
PRINT "spread on toast 1"
PRINT "spread on toast 2"
PRINT "grab tissue"
PRINT "wipe butter off knife"
PRINT "open jam jar"
PRINT "set down lid"
PRINT "equip knife"
PRINT "get 1 scoop of jam"
PRINT "toss jam on bread 1"
PRINT "get 1 scoop of jam"
PRINT "toss jam on bread 2"
PRINT "spread jam bread 1"
PRINT "spread jam bread 2"
PRINT "place knife on tissue"
PRINT "grab jam jar"
PRINT "close jam container"
PRINT "walk to fridge"
PRINT "open fridge"
PRINT "store jam jar"
PRINT "close fridge"
PRINT "walk to sink"
PRINT "grab used knife"
PRINT "rinse knife"
PRINT "wipe knife with tissue"
PRINT "open utensil drawer"
PRINT "set knife back"
PRINT "close drawer"
PRINT "hear kettle wistling"
PRINT "turn off stove"
PRINT "grab kettle off stove"
PRINT "open top of kettle"
PRINT "place top on counter"
PRINT "pour water into coffee cup"
PRINT "set kettle back down"
PRINT "turn off stove lights"
PRINT "grab nearby toast plate: hold R hand"
PRINT "tuck water cup: under R arm"
PRINT "grab coffee cup: hold L hand"
PRINT "slowly walk down stairs"
PRINT "turn left"
PRINT "enter half closed: office door"
PRINT "place coffee cup on desk"
PRINT "place toast plate on 2nd desk"
PRINT "walk back out door"
PRINT "turn L down hallway"
PRINT "enter: restroom door"
PRINT "grab brush"
PRINT "brush hair"
PRINT "set down brush"
PRINT "other stuff if needed"
PRINT "exit: restroom door"
PRINT "walk down hallway"
PRINT "turn R"
PRINT "enter: office door"
PRINT "walk around to chair"
PRINT "sit down"
PRINT "move keyboard backwards"
PRINT "place knitted coaster there"
PRINT "turn R grab toast plate RH"
PRINT "grab coffee cup LH"
PRINT "turn L (center) place plate on coaster"
PRINT "set coffee cup on corner desk"
PRINT "face monitor (center)"
PRINT "put on DT 770 headphones"
PRINT "play (tv media of choice)"
PRINT "sit back in chair"
PRINT "eat toast in intervals"
PRINT "continue watching (media)"
PRINT "sip coffee when it's not too hot"
PRINT "finish eating"
PRINT "pick up plate"
PRINT "turn R: using R hand"
PRINT "place plate on 2nd desk"
PRINT "turn L (center)"
PRINT "store coaster on left shelf"
PRINT "align keyboard back"
PRINT "grab coffee cup"
PRINT "set on main desk (center)"
PRINT "finish rest of episode (media)"
PRINT "consider watching more..."
PRINT "if Y: watch another one"
PRINT "sip coffee"
PRINT "click next episode"
PRINT "finish"
PRINT "update stat sheet"
PRINT "close browser"
PRINT "if N: update stat sheet"
PRINT "close browser"
PRINT "sip coffee"
PRINT "check discord again"
PRINT "check online friends on battle.net app"
PRINT "consider which game I want to grind"
PRINT "9/10 times, select Games tab"
PRINT "click on Overwatch"
PRINT "load up game"
PRINT "readjust periferials"
PRINT "stretch hands and arms"
PRINT "finish off coffee"
PRINT "hop in training tool"
PRINT "warm up aim quick"
PRINT "consider my goals for the session"
PRINT "find a group for competitive"
PRINT "choose role and a meta hero"
PRINT "commense farming session"
PRINT "after I lose one game or run out of time"
PRINT "exit game"
PRINT "stare at desktop :thinking:"
PRINT "relax for a bit"
PRINT "open/listen to music"
PRINT "check time"
PRINT "decide to leave house in ~1 hour"
PRINT "load up rhythm game of choice: osu"
PRINT "tab out"
PRINT "grab graphical tablet (corner desk)"
PRINT "shove over keyboard slightly"
PRINT "shove over mouse"
PRINT "place tablet (R center desk)"
PRINT "align tablet"
PRINT "reach right"
PRINT " grab cable"
PRINT "plug into tablet"
PRINT "grab tablet pen"
PRINT "find tablet pen grip"
PRINT "restart tablet driver"
PRINT "tab back in to game"
PRINT "begin warming up offline"
PRINT "log in later/go online"
PRINT "try for some good scores"
PRINT "if im performing poorly: exit game"
PRINT "if im performing well: play until 9:00"
PRINT "at 9:00 quit game"
PRINT "stand up"
PRINT "walk around corner desk"
PRINT "exit: room"
PRINT "walk through hallway"
PRINT "turn R"
PRINT "enter: restroom door"
PRINT "grab toothbrush"
PRINT "grab toothpaste"
PRINT "turn on water"
PRINT "spread toothpaste"
PRINT "wet toothbrush"
PRINT "brush teeth"
PRINT "set back toothbrush/paste"
PRINT "look into mirror"
PRINT "fix up hair"
PRINT "weight hair down"
PRINT "exit: restroom"
PRINT "walk through hallway"
PRINT "turn R"
PRINT "enter: office door"
PRINT "walk around corner desk"
PRINT "sit down in lounge chair"
PRINT "grab nearby main bag"
PRINT "stand up"
PRINT "sling it over shoulder"
PRINT "stand up"
PRINT " walk to north wall"
PRINT "grab shoes"
PRINT "walk back"
PRINT "sit down on same chair"
PRINT "equip shoe left"
PRINT "equip shoe right"
PRINT "stand up"
PRINT "walk around computer chair"
PRINT "reach to main desk"
PRINT "grab phone off stand"
PRINT "place phone in front R pocket"
PRINT "rotate L"
PRINT "hold half of bag"
PRINT "unzip front pocket on bag"
PRINT "grab microcloth"
PRINT "take glasses off"
PRINT "gently clean glasses with cloth"
PRINT "place glasses on head"
PRINT "rotate back L"
PRINT "put cloth in bag"
PRINT "zip up bag pocket"
PRINT "walk around corner desk"
PRINT "turn L"
PRINT "exit: office door"
PRINT "turn R"
PRINT "walk up stairs"
PRINT "turn L"
PRINT "walk to kitchen"
PRINT "walk to fridge"
PRINT "open fridge"
PRINT "grab lunch bag"
PRINT "close fridge"
PRINT "rotate L"
PRINT "open main pocket on bag"
PRINT "place lunch kit in bag"
PRINT "adjust for comfort"
PRINT "close main pocket"
PRINT "turn R"
PRINT "walk down stairs halfway"
PRINT "turn R"
PRINT "enter: garage door"
PRINT "rotate L"
PRINT "grab plastic water bottle on shelf"
PRINT "rotate L"
PRINT "hold bag"
PRINT "open main pocket of bag"
PRINT "place water bottle in bag"
PRINT "adjust for comfort"
PRINT "close main bag"
PRINT "walk forward"
PRINT "swing open R door of car"
PRINT "sit passenger seat"
PRINT "close car down"
PRINT "rotate R"
PRINT "remove bag from shoulder"
PRINT "place bag on L side of L leg"
PRINT "reach to top R corner"
PRINT "grab seatbelt"
PRINT "look L"
PRINT "click in seatbelt"
PRINT "open garage"
PRINT "drive into the sunset"
END
